// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package platformdb

import (
	"context"
)

type Querier interface {
	//AcquireControlPlaneLease
	//
	//  INSERT INTO control_plane_leases (
	//      lease_name,
	//      holder_id,
	//      expires_at,
	//      updated_at
	//  )
	//  VALUES (
	//      ?1,
	//      ?2,
	//      ?3,
	//      ?4
	//  )
	//  ON CONFLICT(lease_name) DO UPDATE SET
	//      holder_id = excluded.holder_id,
	//      expires_at = excluded.expires_at,
	//      updated_at = excluded.updated_at
	//  WHERE control_plane_leases.holder_id = excluded.holder_id
	//      OR control_plane_leases.expires_at <= excluded.updated_at
	//  RETURNING holder_id
	AcquireControlPlaneLease(ctx context.Context, arg AcquireControlPlaneLeaseParams) (string, error)
	//ActivateMemoryBankProjectShare
	//
	//  UPDATE memory_bank_project_shares
	//  SET state = 'active',
	//      accepted_at = ?1,
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE share_id = ?2
	//    AND collaborator_subject_sub = ?3
	//    AND state IN ('pending', 'active')
	//    AND (expires_at IS NULL OR julianday(expires_at) > julianday(?1))
	//    AND EXISTS (
	//      SELECT 1
	//      FROM memory_bank_projects
	//      WHERE memory_bank_projects.project_id = memory_bank_project_shares.project_id
	//        AND memory_bank_projects.archived_at IS NULL
	//    )
	ActivateMemoryBankProjectShare(ctx context.Context, arg ActivateMemoryBankProjectShareParams) (int64, error)
	//AllowedServiceGrant
	//
	//  SELECT EXISTS (
	//      SELECT 1
	//      FROM service_grants
	//      JOIN service_catalog ON service_catalog.service_id = service_grants.service_id
	//      WHERE service_grants.subject_sub = ?1
	//        AND service_grants.service_id = ?2
	//        AND service_catalog.enabled = 1
	//  ) AS allowed
	AllowedServiceGrant(ctx context.Context, arg AllowedServiceGrantParams) (int64, error)
	//ApproveDeviceAuthorization
	//
	//  UPDATE oauth_device_authorizations
	//  SET subject_sub = ?1,
	//      status = 'approved',
	//      approved_at = ?2,
	//      updated_at = ?2
	//  WHERE device_authorization_id = ?3
	//    AND status = 'pending'
	//    AND expires_at > ?4
	ApproveDeviceAuthorization(ctx context.Context, arg ApproveDeviceAuthorizationParams) (int64, error)
	//ConsumeDeviceAuthorization
	//
	//  UPDATE oauth_device_authorizations
	//  SET status = 'consumed',
	//      consumed_at = ?1,
	//      updated_at = ?1
	//  WHERE device_authorization_id = ?2
	//    AND status = 'approved'
	//    AND subject_sub IS NOT NULL
	//    AND expires_at > ?3
	ConsumeDeviceAuthorization(ctx context.Context, arg ConsumeDeviceAuthorizationParams) (int64, error)
	//ConsumeOAuthSessionByCodeHash
	//
	//  UPDATE oauth_sessions
	//  SET consumed_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
	//  WHERE authorization_code_hash = ?1 AND consumed_at IS NULL
	//  RETURNING session_id, subject_sub, client_id, service_id, resource, redirect_uri, scope, code_challenge, code_challenge_method, authorization_code_hash, authorization_code_ciphertext, access_token_hash, access_token_ciphertext, refresh_token_hash, refresh_token_ciphertext, code_create_at, code_expires_in_seconds, access_create_at, access_expires_in_seconds, refresh_create_at, refresh_expires_in_seconds, expires_at, issued_via, operator_reason, authorization_details, policy_binding_id, share_id
	ConsumeOAuthSessionByCodeHash(ctx context.Context, arg ConsumeOAuthSessionByCodeHashParams) (ConsumeOAuthSessionByCodeHashRow, error)
	//ConsumeOAuthSessionByRefreshHash
	//
	//  UPDATE oauth_sessions
	//  SET consumed_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
	//  WHERE refresh_token_hash = ?1 AND consumed_at IS NULL
	//  RETURNING session_id, subject_sub, client_id, service_id, resource, redirect_uri, scope, code_challenge, code_challenge_method, authorization_code_hash, authorization_code_ciphertext, access_token_hash, access_token_ciphertext, refresh_token_hash, refresh_token_ciphertext, code_create_at, code_expires_in_seconds, access_create_at, access_expires_in_seconds, refresh_create_at, refresh_expires_in_seconds, expires_at, issued_via, operator_reason, authorization_details, policy_binding_id, share_id
	ConsumeOAuthSessionByRefreshHash(ctx context.Context, arg ConsumeOAuthSessionByRefreshHashParams) (ConsumeOAuthSessionByRefreshHashRow, error)
	//CountAllowedServiceGrants
	//
	//  SELECT COUNT(DISTINCT service_grants.service_id) AS allowed_count
	//  FROM service_grants
	//  JOIN service_catalog ON service_catalog.service_id = service_grants.service_id
	//  WHERE service_grants.subject_sub = ?1
	//    AND service_catalog.enabled = 1
	//    AND service_grants.service_id IN (/*SLICE:service_ids*/?)
	CountAllowedServiceGrants(ctx context.Context, arg CountAllowedServiceGrantsParams) (int64, error)
	//CountAuditEventsByType
	//
	//  SELECT COUNT(*) AS audit_count
	//  FROM audit_events
	//  WHERE event_type = ?1
	CountAuditEventsByType(ctx context.Context, arg CountAuditEventsByTypeParams) (int64, error)
	//CountSubjectServiceGrant
	//
	//  SELECT COUNT(*)
	//  FROM service_grants
	//  JOIN service_catalog ON service_catalog.service_id = service_grants.service_id
	//  WHERE service_grants.subject_sub = ?1
	//    AND service_grants.service_id = ?2
	//    AND service_catalog.enabled = 1
	CountSubjectServiceGrant(ctx context.Context, arg CountSubjectServiceGrantParams) (int64, error)
	//CreateDeviceAuthorization
	//
	//  INSERT INTO oauth_device_authorizations (
	//      device_authorization_id,
	//      client_id,
	//      service_id,
	//      resource,
	//      scope,
	//      device_code_hash,
	//      user_code_hash,
	//      user_code_display,
	//      status,
	//      interval_seconds,
	//      expires_at,
	//      created_at,
	//      updated_at
	//  )
	//  VALUES (
	//      ?1,
	//      ?2,
	//      ?3,
	//      ?4,
	//      ?5,
	//      ?6,
	//      ?7,
	//      ?8,
	//      'pending',
	//      ?9,
	//      ?10,
	//      ?11,
	//      ?11
	//  )
	CreateDeviceAuthorization(ctx context.Context, arg CreateDeviceAuthorizationParams) error
	//CreateOAuthClient
	//
	//  INSERT INTO oauth_clients (client_id, client_name, created_by_subject_sub, redirect_uris, grant_types, response_types, scopes, token_endpoint_auth_method, client_secret_hash, metadata, created_at, updated_at)
	//  VALUES (?1, ?2, NULLIF(?3, ''), ?4, ?5, ?6, ?7, ?8, ?9, '{}', ?10, ?10)
	CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) error
	//DeleteAllServiceGrants
	//
	//  DELETE FROM service_grant_sources WHERE source_group <> 'manual'
	DeleteAllServiceGrants(ctx context.Context) error
	//DeleteBrowserSession
	//
	//  DELETE FROM edge_browser_sessions WHERE session_id = ?1
	DeleteBrowserSession(ctx context.Context, arg DeleteBrowserSessionParams) error
	//DeleteManualServiceGrantSource
	//
	//  DELETE FROM service_grant_sources
	//  WHERE subject_sub = ?1
	//    AND service_id = ?2
	//    AND source_group = 'manual'
	DeleteManualServiceGrantSource(ctx context.Context, arg DeleteManualServiceGrantSourceParams) error
	//DeleteOAuthSessionByAccessHash
	//
	//  DELETE FROM oauth_sessions WHERE access_token_hash = ?1
	DeleteOAuthSessionByAccessHash(ctx context.Context, arg DeleteOAuthSessionByAccessHashParams) error
	//DeleteOAuthSessionByCodeHash
	//
	//  DELETE FROM oauth_sessions WHERE authorization_code_hash = ?1
	DeleteOAuthSessionByCodeHash(ctx context.Context, arg DeleteOAuthSessionByCodeHashParams) error
	//DeleteOAuthSessionByRefreshHash
	//
	//  DELETE FROM oauth_sessions WHERE refresh_token_hash = ?1
	DeleteOAuthSessionByRefreshHash(ctx context.Context, arg DeleteOAuthSessionByRefreshHashParams) error
	//DeleteOperatorOAuthSessionByID
	//
	//  DELETE FROM oauth_sessions
	//  WHERE session_id = ?1
	//    AND issued_via = 'operator'
	//    AND client_id = ?2
	DeleteOperatorOAuthSessionByID(ctx context.Context, arg DeleteOperatorOAuthSessionByIDParams) (int64, error)
	//DeletePendingLogin
	//
	//  DELETE FROM edge_pending_logins WHERE state = ?1
	DeletePendingLogin(ctx context.Context, arg DeletePendingLoginParams) error
	//DeleteStaleServiceGrants
	//
	//  DELETE FROM service_grant_sources
	//  WHERE source_group <> 'manual'
	//    AND subject_sub NOT IN (/*SLICE:subject_subs*/?)
	DeleteStaleServiceGrants(ctx context.Context, arg DeleteStaleServiceGrantsParams) error
	//DeleteSubjectGrantSources
	//
	//  DELETE FROM service_grant_sources WHERE subject_sub = ?1
	DeleteSubjectGrantSources(ctx context.Context, arg DeleteSubjectGrantSourcesParams) error
	//DeleteSubjectGrants
	//
	//  DELETE FROM service_grants WHERE subject_sub = ?1
	DeleteSubjectGrants(ctx context.Context, arg DeleteSubjectGrantsParams) error
	//DeleteSubjectSyncedGrantSources
	//
	//  DELETE FROM service_grant_sources
	//  WHERE subject_sub = ?1
	//    AND source_group <> 'manual'
	DeleteSubjectSyncedGrantSources(ctx context.Context, arg DeleteSubjectSyncedGrantSourcesParams) error
	//DeleteTenantInstance
	//
	//  DELETE FROM tenant_instances WHERE tenant_id = ?1
	DeleteTenantInstance(ctx context.Context, arg DeleteTenantInstanceParams) error
	//DenyDeviceAuthorization
	//
	//  UPDATE oauth_device_authorizations
	//  SET status = 'denied',
	//      denied_at = ?1,
	//      updated_at = ?1
	//  WHERE device_authorization_id = ?2
	//    AND status = 'pending'
	//    AND expires_at > ?3
	DenyDeviceAuthorization(ctx context.Context, arg DenyDeviceAuthorizationParams) (int64, error)
	//DisableAllBuiltinServiceCatalogEntries
	//
	//  UPDATE service_catalog
	//  SET enabled = 0,
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE source = 'builtin'
	DisableAllBuiltinServiceCatalogEntries(ctx context.Context) error
	//DisableServiceCatalogEntriesNotIn
	//
	//  UPDATE service_catalog
	//  SET enabled = 0,
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE service_id NOT IN (/*SLICE:service_ids*/?)
	//    AND source = 'builtin'
	DisableServiceCatalogEntriesNotIn(ctx context.Context, arg DisableServiceCatalogEntriesNotInParams) error
	//DisableServiceCatalogEntry
	//
	//  UPDATE service_catalog
	//  SET enabled = 0,
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE service_id = ?1
	DisableServiceCatalogEntry(ctx context.Context, arg DisableServiceCatalogEntryParams) error
	//EdgeUpsertSubject
	//
	//  INSERT INTO subjects (subject_sub, subject_key, preferred_username, email, display_name, account_binding_id, account_binding_claim, last_synced_at, created_at, updated_at)
	//  VALUES (?1, ?2, NULLIF(?3, ''), NULLIF(?4, ''), NULLIF(?5, ''), NULLIF(?6, ''), NULLIF(?7, ''), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
	//  ON CONFLICT(subject_sub) DO UPDATE SET
	//      subject_key = excluded.subject_key,
	//      preferred_username = COALESCE(excluded.preferred_username, subjects.preferred_username),
	//      email = COALESCE(excluded.email, subjects.email),
	//      display_name = COALESCE(excluded.display_name, subjects.display_name),
	//      account_binding_id = COALESCE(excluded.account_binding_id, subjects.account_binding_id),
	//      account_binding_claim = COALESCE(excluded.account_binding_claim, subjects.account_binding_claim),
	//      last_synced_at = CURRENT_TIMESTAMP,
	//      updated_at = CURRENT_TIMESTAMP
	EdgeUpsertSubject(ctx context.Context, arg EdgeUpsertSubjectParams) error
	//EnableTenantInstance
	//
	//  UPDATE tenant_instances
	//  SET subject_key = ?1,
	//      tenant_instance_name = ?2,
	//      internal_dns_name = ?3,
	//      desired_state = ?4,
	//      runtime_state = ?5,
	//      last_error = NULLIF(?6, ''),
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE tenant_id = ?7
	EnableTenantInstance(ctx context.Context, arg EnableTenantInstanceParams) error
	//ExpireMemoryBankProjectShares
	//
	//  UPDATE memory_bank_project_shares
	//  SET state = 'expired',
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE state IN ('pending', 'active')
	//    AND expires_at IS NOT NULL
	//    AND julianday(expires_at) <= julianday(?1)
	ExpireMemoryBankProjectShares(ctx context.Context, arg ExpireMemoryBankProjectSharesParams) (int64, error)
	//GetBrowserSession
	//
	//  SELECT claims, expires_at
	//  FROM edge_browser_sessions
	//  WHERE session_id = ?1
	GetBrowserSession(ctx context.Context, arg GetBrowserSessionParams) (GetBrowserSessionRow, error)
	//GetDeviceAuthorizationByDeviceCodeHash
	//
	//  SELECT device_authorization_id,
	//         client_id,
	//         subject_sub,
	//         service_id,
	//         resource,
	//         scope,
	//         device_code_hash,
	//         user_code_hash,
	//         user_code_display,
	//         status,
	//         interval_seconds,
	//         last_poll_at,
	//         poll_count,
	//         approved_at,
	//         denied_at,
	//         expires_at,
	//         consumed_at,
	//         created_at,
	//         updated_at
	//  FROM oauth_device_authorizations
	//  WHERE device_code_hash = ?1
	GetDeviceAuthorizationByDeviceCodeHash(ctx context.Context, arg GetDeviceAuthorizationByDeviceCodeHashParams) (OauthDeviceAuthorization, error)
	//GetDeviceAuthorizationByUserCodeHash
	//
	//  SELECT device_authorization_id,
	//         client_id,
	//         subject_sub,
	//         service_id,
	//         resource,
	//         scope,
	//         device_code_hash,
	//         user_code_hash,
	//         user_code_display,
	//         status,
	//         interval_seconds,
	//         last_poll_at,
	//         poll_count,
	//         approved_at,
	//         denied_at,
	//         expires_at,
	//         consumed_at,
	//         created_at,
	//         updated_at
	//  FROM oauth_device_authorizations
	//  WHERE user_code_hash = ?1
	GetDeviceAuthorizationByUserCodeHash(ctx context.Context, arg GetDeviceAuthorizationByUserCodeHashParams) (OauthDeviceAuthorization, error)
	//GetEnabledServiceCatalogEntry
	//
	//  SELECT service_id,
	//      display_name,
	//      upstream_service_name,
	//      transport_type,
	//      internal_port,
	//      public_path,
	//      internal_upstream_path,
	//      health_path,
	//      health_probe_expectation,
	//      resource_profile,
	//      persistence_policy,
	//      adapter_requirement,
	//      secret_contract,
	//      identity_context,
	//      enabled,
	//      source,
	//      created_at,
	//      updated_at
	//  FROM service_catalog
	//  WHERE service_id = ?1
	//    AND enabled = 1
	GetEnabledServiceCatalogEntry(ctx context.Context, arg GetEnabledServiceCatalogEntryParams) (GetEnabledServiceCatalogEntryRow, error)
	//GetLatestTenantRuntimeAttestation
	//
	//  SELECT attestation_id,
	//         tenant_id,
	//         spec_id,
	//         measurement_id,
	//         policy_version,
	//         verdict,
	//         failure_reasons_json,
	//         expires_at,
	//         created_at
	//  FROM tenant_runtime_attestations
	//  WHERE tenant_id = ?1
	//  ORDER BY created_at DESC, rowid DESC
	//  LIMIT 1
	GetLatestTenantRuntimeAttestation(ctx context.Context, arg GetLatestTenantRuntimeAttestationParams) (TenantRuntimeAttestation, error)
	//GetMemoryBankProject
	//
	//  SELECT project_id,
	//         owner_subject_sub,
	//         owner_tenant_id,
	//         service_id,
	//         project_key,
	//         display_name,
	//         root_path,
	//         metadata,
	//         archived_at,
	//         created_at,
	//         updated_at
	//  FROM memory_bank_projects
	//  WHERE project_id = ?1
	GetMemoryBankProject(ctx context.Context, arg GetMemoryBankProjectParams) (MemoryBankProject, error)
	//GetMemoryBankProjectByOwnerKey
	//
	//  SELECT project_id,
	//         owner_subject_sub,
	//         owner_tenant_id,
	//         service_id,
	//         project_key,
	//         display_name,
	//         root_path,
	//         metadata,
	//         archived_at,
	//         created_at,
	//         updated_at
	//  FROM memory_bank_projects
	//  WHERE owner_subject_sub = ?1
	//    AND service_id = ?2
	//    AND project_key = ?3
	GetMemoryBankProjectByOwnerKey(ctx context.Context, arg GetMemoryBankProjectByOwnerKeyParams) (MemoryBankProject, error)
	//GetMemoryBankProjectShare
	//
	//  SELECT share_id,
	//         memory_bank_project_shares.project_id,
	//         memory_bank_project_shares.owner_subject_sub,
	//         memory_bank_project_shares.collaborator_subject_sub,
	//         memory_bank_project_shares.permission,
	//         memory_bank_project_shares.state,
	//         memory_bank_project_shares.source,
	//         memory_bank_project_shares.created_by_subject_sub,
	//         memory_bank_project_shares.accepted_at,
	//         memory_bank_project_shares.revoked_at,
	//         memory_bank_project_shares.expires_at,
	//         memory_bank_project_shares.metadata,
	//         memory_bank_project_shares.created_at,
	//         memory_bank_project_shares.updated_at
	//  FROM memory_bank_project_shares
	//  WHERE share_id = ?1
	GetMemoryBankProjectShare(ctx context.Context, arg GetMemoryBankProjectShareParams) (MemoryBankProjectShare, error)
	//GetOAuthClient
	//
	//  SELECT redirect_uris, grant_types, scopes, created_by_subject_sub, token_endpoint_auth_method, client_secret_hash, disabled_at
	//  FROM oauth_clients
	//  WHERE client_id = ?1
	GetOAuthClient(ctx context.Context, arg GetOAuthClientParams) (GetOAuthClientRow, error)
	//GetOAuthSessionByAccessHash
	//
	//  SELECT session_id, subject_sub, client_id, service_id, resource, redirect_uri, scope, code_challenge, code_challenge_method, authorization_code_hash, authorization_code_ciphertext, access_token_hash, access_token_ciphertext, refresh_token_hash, refresh_token_ciphertext, code_create_at, code_expires_in_seconds, access_create_at, access_expires_in_seconds, refresh_create_at, refresh_expires_in_seconds, expires_at, issued_via, operator_reason, authorization_details, policy_binding_id, share_id
	//  FROM oauth_sessions
	//  WHERE access_token_hash = ?1
	GetOAuthSessionByAccessHash(ctx context.Context, arg GetOAuthSessionByAccessHashParams) (GetOAuthSessionByAccessHashRow, error)
	//GetOAuthSessionByCodeHash
	//
	//  SELECT session_id, subject_sub, client_id, service_id, resource, redirect_uri, scope, code_challenge, code_challenge_method, authorization_code_hash, authorization_code_ciphertext, access_token_hash, access_token_ciphertext, refresh_token_hash, refresh_token_ciphertext, code_create_at, code_expires_in_seconds, access_create_at, access_expires_in_seconds, refresh_create_at, refresh_expires_in_seconds, expires_at, issued_via, operator_reason, authorization_details, policy_binding_id, share_id
	//  FROM oauth_sessions
	//  WHERE authorization_code_hash = ?1 AND consumed_at IS NULL
	GetOAuthSessionByCodeHash(ctx context.Context, arg GetOAuthSessionByCodeHashParams) (GetOAuthSessionByCodeHashRow, error)
	//GetOAuthSessionByRefreshHash
	//
	//  SELECT session_id, subject_sub, client_id, service_id, resource, redirect_uri, scope, code_challenge, code_challenge_method, authorization_code_hash, authorization_code_ciphertext, access_token_hash, access_token_ciphertext, refresh_token_hash, refresh_token_ciphertext, code_create_at, code_expires_in_seconds, access_create_at, access_expires_in_seconds, refresh_create_at, refresh_expires_in_seconds, expires_at, issued_via, operator_reason, authorization_details, policy_binding_id, share_id
	//  FROM oauth_sessions
	//  WHERE refresh_token_hash = ?1
	GetOAuthSessionByRefreshHash(ctx context.Context, arg GetOAuthSessionByRefreshHashParams) (GetOAuthSessionByRefreshHashRow, error)
	//GetPendingLogin
	//
	//  SELECT state, return_to, nonce, expires_at
	//  FROM edge_pending_logins
	//  WHERE state = ?1
	GetPendingLogin(ctx context.Context, arg GetPendingLoginParams) (GetPendingLoginRow, error)
	//GetServiceCatalogEntry
	//
	//  SELECT service_id,
	//      display_name,
	//      upstream_service_name,
	//      transport_type,
	//      internal_port,
	//      public_path,
	//      internal_upstream_path,
	//      health_path,
	//      health_probe_expectation,
	//      resource_profile,
	//      persistence_policy,
	//      adapter_requirement,
	//      secret_contract,
	//      identity_context,
	//      enabled,
	//      source,
	//      created_at,
	//      updated_at
	//  FROM service_catalog
	//  WHERE service_id = ?1
	GetServiceCatalogEntry(ctx context.Context, arg GetServiceCatalogEntryParams) (GetServiceCatalogEntryRow, error)
	//GetSubject
	//
	//  SELECT subject_sub,
	//         subject_key,
	//         preferred_username,
	//         email,
	//         display_name,
	//         account_binding_id,
	//         account_binding_claim
	//  FROM subjects
	//  WHERE subject_sub = ?1
	GetSubject(ctx context.Context, arg GetSubjectParams) (GetSubjectRow, error)
	//GetTenantInstance
	//
	//  SELECT tenant_id,
	//         subject_sub,
	//         service_id,
	//         subject_key,
	//         tenant_instance_name,
	//         internal_dns_name,
	//         desired_state,
	//         runtime_state,
	//         coolify_resource_id,
	//         coolify_application_id,
	//         upstream_url,
	//         secret_version,
	//         last_healthy_at,
	//         last_reconciled_at,
	//         last_error,
	//         metadata,
	//         attestation_state,
	//         last_attested_at,
	//         last_attestation_id,
	//         runtime_spec_id,
	//         created_at,
	//         updated_at
	//  FROM tenant_instances
	//  WHERE tenant_id = ?1
	GetTenantInstance(ctx context.Context, arg GetTenantInstanceParams) (GetTenantInstanceRow, error)
	//GetTenantInstanceBySubjectService
	//
	//  SELECT tenant_id,
	//         subject_sub,
	//         service_id,
	//         subject_key,
	//         tenant_instance_name,
	//         internal_dns_name,
	//         desired_state,
	//         runtime_state,
	//         coolify_resource_id,
	//         coolify_application_id,
	//         upstream_url,
	//         secret_version,
	//         last_healthy_at,
	//         last_reconciled_at,
	//         last_error,
	//         metadata,
	//         attestation_state,
	//         last_attested_at,
	//         last_attestation_id,
	//         runtime_spec_id,
	//         created_at,
	//         updated_at
	//  FROM tenant_instances
	//  WHERE subject_sub = ?1
	//    AND service_id = ?2
	//    AND desired_state <> 'deleted'
	GetTenantInstanceBySubjectService(ctx context.Context, arg GetTenantInstanceBySubjectServiceParams) (GetTenantInstanceBySubjectServiceRow, error)
	//GetTenantRuntimeAttestation
	//
	//  SELECT attestation_id,
	//         tenant_id,
	//         spec_id,
	//         measurement_id,
	//         policy_version,
	//         verdict,
	//         failure_reasons_json,
	//         expires_at,
	//         created_at
	//  FROM tenant_runtime_attestations
	//  WHERE attestation_id = ?1
	GetTenantRuntimeAttestation(ctx context.Context, arg GetTenantRuntimeAttestationParams) (TenantRuntimeAttestation, error)
	//GetTenantRuntimeMeasurement
	//
	//  SELECT measurement_id,
	//         tenant_id,
	//         coolify_resource_id,
	//         container_id,
	//         source,
	//         image_ref,
	//         image_digest,
	//         compose_hash,
	//         env_contract_hash,
	//         network_json,
	//         ports_json,
	//         volumes_json,
	//         health_status,
	//         raw_summary_json,
	//         measured_at
	//  FROM tenant_runtime_measurements
	//  WHERE measurement_id = ?1
	GetTenantRuntimeMeasurement(ctx context.Context, arg GetTenantRuntimeMeasurementParams) (TenantRuntimeMeasurement, error)
	//GetTenantRuntimeSpec
	//
	//  SELECT spec_id,
	//         tenant_id,
	//         service_id,
	//         subject_sub,
	//         spec_version,
	//         compose_hash,
	//         env_contract_hash,
	//         secret_contract_hash,
	//         image_refs_json,
	//         network_policy_json,
	//         identity_context_hash,
	//         created_at
	//  FROM tenant_runtime_specs
	//  WHERE spec_id = ?1
	GetTenantRuntimeSpec(ctx context.Context, arg GetTenantRuntimeSpecParams) (TenantRuntimeSpec, error)
	//GetTenantUpstream
	//
	//  SELECT COALESCE(upstream_url, '') AS upstream_url,
	//         internal_dns_name,
	//         desired_state,
	//         runtime_state,
	//         metadata
	//  FROM tenant_instances
	//  WHERE subject_sub = ?1
	//    AND service_id = ?2
	GetTenantUpstream(ctx context.Context, arg GetTenantUpstreamParams) (GetTenantUpstreamRow, error)
	//InsertAuditEvent
	//
	//  INSERT INTO audit_events (event_id, correlation_id, actor_subject_sub, service_id, event_type, event_status, payload)
	//  VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error
	//InsertEffectiveServiceGrantsFromSources
	//
	//  INSERT INTO service_grants (subject_sub, service_id, source_group, granted_at, last_synced_at)
	//  SELECT subject_sub,
	//         service_id,
	//         CASE WHEN SUM(CASE WHEN source_group = 'manual' THEN 1 ELSE 0 END) > 0 THEN 'manual' ELSE MIN(source_group) END AS source_group,
	//         MIN(granted_at) AS granted_at,
	//         MAX(last_synced_at) AS last_synced_at
	//  FROM service_grant_sources
	//  GROUP BY subject_sub, service_id
	InsertEffectiveServiceGrantsFromSources(ctx context.Context) error
	//InsertMemoryBankProjectShare
	//
	//  INSERT INTO memory_bank_project_shares (share_id, project_id, owner_subject_sub, collaborator_subject_sub, permission, state, source, created_by_subject_sub, expires_at, metadata)
	//  SELECT ?1,
	//         ?2,
	//         ?3,
	//         ?4,
	//         ?5,
	//         ?6,
	//         ?7,
	//         ?8,
	//         ?9,
	//         ?10
	//  FROM memory_bank_projects
	//  WHERE project_id = ?2
	//    AND owner_subject_sub = ?3
	//    AND archived_at IS NULL
	InsertMemoryBankProjectShare(ctx context.Context, arg InsertMemoryBankProjectShareParams) (int64, error)
	//InsertReconcileRun
	//
	//  INSERT INTO reconcile_runs (run_id, tenant_id, desired_state, observed_state, action, status, details, started_at, finished_at)
	//  VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
	InsertReconcileRun(ctx context.Context, arg InsertReconcileRunParams) error
	//InsertServiceGrantSource
	//
	//  INSERT INTO service_grant_sources (subject_sub, service_id, source_group, granted_at, last_synced_at)
	//  VALUES (?1, ?2, ?3, ?4, ?5)
	//  ON CONFLICT(subject_sub, service_id, source_group) DO UPDATE SET
	//      last_synced_at = excluded.last_synced_at,
	//      updated_at = CURRENT_TIMESTAMP
	InsertServiceGrantSource(ctx context.Context, arg InsertServiceGrantSourceParams) error
	//InsertTenantInstance
	//
	//  INSERT INTO tenant_instances (tenant_id, subject_sub, service_id, subject_key, tenant_instance_name, internal_dns_name, desired_state, runtime_state)
	//  VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
	InsertTenantInstance(ctx context.Context, arg InsertTenantInstanceParams) error
	//InsertTenantRuntimeAttestation
	//
	//  INSERT INTO tenant_runtime_attestations (attestation_id, tenant_id, spec_id, measurement_id, policy_version, verdict, failure_reasons_json, expires_at, created_at)
	//  VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
	InsertTenantRuntimeAttestation(ctx context.Context, arg InsertTenantRuntimeAttestationParams) error
	//InsertTenantRuntimeMeasurement
	//
	//  INSERT INTO tenant_runtime_measurements (measurement_id, tenant_id, coolify_resource_id, container_id, source, image_ref, image_digest, compose_hash, env_contract_hash, network_json, ports_json, volumes_json, health_status, raw_summary_json, measured_at)
	//  VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15)
	InsertTenantRuntimeMeasurement(ctx context.Context, arg InsertTenantRuntimeMeasurementParams) error
	//InsertTenantRuntimeSpec
	//
	//  INSERT INTO tenant_runtime_specs (spec_id, tenant_id, service_id, subject_sub, spec_version, compose_hash, env_contract_hash, secret_contract_hash, image_refs_json, network_policy_json, identity_context_hash, created_at)
	//  VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12)
	InsertTenantRuntimeSpec(ctx context.Context, arg InsertTenantRuntimeSpecParams) error
	//ListDesiredTenantSpecs
	//
	//  SELECT subjects.subject_sub,
	//         subjects.subject_key,
	//         COALESCE(subjects.preferred_username, '') AS preferred_username,
	//         COALESCE(subjects.email, '') AS email,
	//         COALESCE(subjects.display_name, '') AS display_name,
	//         COALESCE(subjects.account_binding_id, '') AS account_binding_id,
	//         COALESCE(subjects.account_binding_claim, '') AS account_binding_claim,
	//         service_grants.service_id
	//  FROM service_grants
	//  JOIN subjects ON subjects.subject_sub = service_grants.subject_sub
	//  JOIN service_catalog ON service_catalog.service_id = service_grants.service_id
	//  WHERE service_catalog.enabled = 1
	//    AND service_catalog.source = 'builtin'
	//  ORDER BY service_grants.service_id, subjects.subject_sub
	ListDesiredTenantSpecs(ctx context.Context) ([]ListDesiredTenantSpecsRow, error)
	//ListEnabledServiceCatalog
	//
	//  SELECT service_id,
	//      display_name,
	//      upstream_service_name,
	//      transport_type,
	//      internal_port,
	//      public_path,
	//      internal_upstream_path,
	//      health_path,
	//      health_probe_expectation,
	//      resource_profile,
	//      persistence_policy,
	//      adapter_requirement,
	//      secret_contract,
	//      identity_context,
	//      enabled,
	//      source,
	//      created_at,
	//      updated_at
	//  FROM service_catalog
	//  WHERE enabled = 1
	//  ORDER BY service_id
	ListEnabledServiceCatalog(ctx context.Context) ([]ListEnabledServiceCatalogRow, error)
	//ListEnabledServiceIDs
	//
	//  SELECT service_id
	//  FROM service_catalog
	//  WHERE enabled = 1
	//  ORDER BY service_id
	ListEnabledServiceIDs(ctx context.Context) ([]string, error)
	//ListMemoryBankProjectSharesForSubject
	//
	//  SELECT memory_bank_project_shares.share_id,
	//         memory_bank_project_shares.project_id,
	//         memory_bank_project_shares.owner_subject_sub,
	//         memory_bank_project_shares.collaborator_subject_sub,
	//         memory_bank_project_shares.permission,
	//         memory_bank_project_shares.state,
	//         memory_bank_project_shares.source,
	//         memory_bank_project_shares.created_by_subject_sub,
	//         memory_bank_project_shares.accepted_at,
	//         memory_bank_project_shares.revoked_at,
	//         memory_bank_project_shares.expires_at,
	//         memory_bank_project_shares.metadata,
	//         memory_bank_project_shares.created_at,
	//         memory_bank_project_shares.updated_at
	//  FROM memory_bank_project_shares
	//  JOIN memory_bank_projects ON memory_bank_projects.project_id = memory_bank_project_shares.project_id
	//  WHERE memory_bank_project_shares.collaborator_subject_sub = ?1
	//    AND (?2 OR (memory_bank_project_shares.state IN ('pending', 'active') AND (memory_bank_project_shares.expires_at IS NULL OR julianday(memory_bank_project_shares.expires_at) > julianday(?3)) AND memory_bank_projects.archived_at IS NULL))
	//  ORDER BY memory_bank_project_shares.updated_at DESC
	ListMemoryBankProjectSharesForSubject(ctx context.Context, arg ListMemoryBankProjectSharesForSubjectParams) ([]MemoryBankProjectShare, error)
	//ListMemoryBankProjectSharesForSubjectService
	//
	//  SELECT memory_bank_project_shares.share_id,
	//         memory_bank_project_shares.project_id,
	//         memory_bank_project_shares.owner_subject_sub,
	//         memory_bank_project_shares.collaborator_subject_sub,
	//         memory_bank_project_shares.permission,
	//         memory_bank_project_shares.state,
	//         memory_bank_project_shares.source,
	//         memory_bank_project_shares.created_by_subject_sub,
	//         memory_bank_project_shares.accepted_at,
	//         memory_bank_project_shares.revoked_at,
	//         memory_bank_project_shares.expires_at,
	//         memory_bank_project_shares.metadata,
	//         memory_bank_project_shares.created_at,
	//         memory_bank_project_shares.updated_at
	//  FROM memory_bank_project_shares
	//  JOIN memory_bank_projects ON memory_bank_projects.project_id = memory_bank_project_shares.project_id
	//  WHERE memory_bank_project_shares.collaborator_subject_sub = ?1
	//    AND memory_bank_projects.service_id = ?2
	//    AND (?3 OR (memory_bank_project_shares.state IN ('pending', 'active') AND (memory_bank_project_shares.expires_at IS NULL OR julianday(memory_bank_project_shares.expires_at) > julianday(?4)) AND memory_bank_projects.archived_at IS NULL))
	//  ORDER BY memory_bank_project_shares.updated_at DESC
	ListMemoryBankProjectSharesForSubjectService(ctx context.Context, arg ListMemoryBankProjectSharesForSubjectServiceParams) ([]MemoryBankProjectShare, error)
	//ListMemoryBankProjectsByOwner
	//
	//  SELECT project_id,
	//         owner_subject_sub,
	//         owner_tenant_id,
	//         service_id,
	//         project_key,
	//         display_name,
	//         root_path,
	//         metadata,
	//         archived_at,
	//         created_at,
	//         updated_at
	//  FROM memory_bank_projects
	//  WHERE owner_subject_sub = ?1
	//    AND service_id = ?2
	//    AND (?3 OR archived_at IS NULL)
	//  ORDER BY project_key
	ListMemoryBankProjectsByOwner(ctx context.Context, arg ListMemoryBankProjectsByOwnerParams) ([]MemoryBankProject, error)
	//ListServiceCatalog
	//
	//  SELECT service_id,
	//      display_name,
	//      upstream_service_name,
	//      transport_type,
	//      internal_port,
	//      public_path,
	//      internal_upstream_path,
	//      health_path,
	//      health_probe_expectation,
	//      resource_profile,
	//      persistence_policy,
	//      adapter_requirement,
	//      secret_contract,
	//      identity_context,
	//      enabled,
	//      source,
	//      created_at,
	//      updated_at
	//  FROM service_catalog
	//  ORDER BY service_id
	ListServiceCatalog(ctx context.Context) ([]ListServiceCatalogRow, error)
	//ListSubjectServiceGrants
	//
	//  SELECT service_grants.subject_sub,
	//         service_grants.service_id,
	//         service_grants.source_group,
	//         service_grants.granted_at,
	//         service_grants.last_synced_at
	//  FROM service_grants
	//  JOIN service_catalog ON service_catalog.service_id = service_grants.service_id
	//  WHERE service_grants.subject_sub = ?1
	//    AND service_catalog.enabled = 1
	//  ORDER BY service_grants.service_id
	ListSubjectServiceGrants(ctx context.Context, arg ListSubjectServiceGrantsParams) ([]ListSubjectServiceGrantsRow, error)
	//ListTenantInstances
	//
	//  SELECT tenant_id,
	//         subject_sub,
	//         service_id,
	//         subject_key,
	//         tenant_instance_name,
	//         internal_dns_name,
	//         desired_state,
	//         runtime_state,
	//         coolify_resource_id,
	//         coolify_application_id,
	//         upstream_url,
	//         secret_version,
	//         last_healthy_at,
	//         last_reconciled_at,
	//         last_error,
	//         metadata,
	//         attestation_state,
	//         last_attested_at,
	//         last_attestation_id,
	//         runtime_spec_id,
	//         created_at,
	//         updated_at
	//  FROM tenant_instances
	//  ORDER BY service_id, subject_sub
	ListTenantInstances(ctx context.Context) ([]ListTenantInstancesRow, error)
	//ListTenantRuntimeMeasurementsForTenant
	//
	//  SELECT measurement_id,
	//         tenant_id,
	//         coolify_resource_id,
	//         container_id,
	//         source,
	//         image_ref,
	//         image_digest,
	//         compose_hash,
	//         env_contract_hash,
	//         network_json,
	//         ports_json,
	//         volumes_json,
	//         health_status,
	//         raw_summary_json,
	//         measured_at
	//  FROM tenant_runtime_measurements
	//  WHERE tenant_id = ?1
	//  ORDER BY measured_at DESC
	ListTenantRuntimeMeasurementsForTenant(ctx context.Context, arg ListTenantRuntimeMeasurementsForTenantParams) ([]TenantRuntimeMeasurement, error)
	//ListTenantRuntimeSpecsForTenant
	//
	//  SELECT spec_id,
	//         tenant_id,
	//         service_id,
	//         subject_sub,
	//         spec_version,
	//         compose_hash,
	//         env_contract_hash,
	//         secret_contract_hash,
	//         image_refs_json,
	//         network_policy_json,
	//         identity_context_hash,
	//         created_at
	//  FROM tenant_runtime_specs
	//  WHERE tenant_id = ?1
	//  ORDER BY created_at DESC
	ListTenantRuntimeSpecsForTenant(ctx context.Context, arg ListTenantRuntimeSpecsForTenantParams) ([]TenantRuntimeSpec, error)
	//MarkExpiredDeviceAuthorizations
	//
	//  UPDATE oauth_device_authorizations
	//  SET status = 'expired',
	//      updated_at = ?1
	//  WHERE status IN ('pending', 'approved')
	//    AND expires_at <= ?1
	MarkExpiredDeviceAuthorizations(ctx context.Context, arg MarkExpiredDeviceAuthorizationsParams) (int64, error)
	//MarkTenantAttestationSummary
	//
	//  UPDATE tenant_instances
	//  SET attestation_state = ?1,
	//      last_attested_at = ?2,
	//      last_attestation_id = ?3,
	//      runtime_spec_id = CASE WHEN ?4 IS NULL THEN runtime_spec_id ELSE ?4 END,
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE tenant_id = ?5
	MarkTenantAttestationSummary(ctx context.Context, arg MarkTenantAttestationSummaryParams) error
	//MarkTenantDesiredDeleted
	//
	//  UPDATE tenant_instances
	//  SET desired_state = ?1,
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE tenant_id = ?2
	MarkTenantDesiredDeleted(ctx context.Context, arg MarkTenantDesiredDeletedParams) error
	//MarkTenantDesiredDisabledBySubjectService
	//
	//  UPDATE tenant_instances
	//  SET desired_state = 'disabled',
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE tenant_instances.subject_sub = ?1
	//    AND tenant_instances.service_id = ?2
	//    AND tenant_instances.desired_state <> 'deleted'
	MarkTenantDesiredDisabledBySubjectService(ctx context.Context, arg MarkTenantDesiredDisabledBySubjectServiceParams) (int64, error)
	//MarkTenantDesiredEnabledBySubjectServiceWithGrant
	//
	//  UPDATE tenant_instances
	//  SET desired_state = 'enabled',
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE tenant_instances.subject_sub = ?1
	//    AND tenant_instances.service_id = ?2
	//    AND tenant_instances.desired_state <> 'deleted'
	//    AND EXISTS (
	//      SELECT 1
	//      FROM service_grants
	//      JOIN service_catalog ON service_catalog.service_id = service_grants.service_id
	//      WHERE service_grants.subject_sub = tenant_instances.subject_sub
	//        AND service_grants.service_id = tenant_instances.service_id
	//        AND service_catalog.enabled = 1
	//    )
	MarkTenantDesiredEnabledBySubjectServiceWithGrant(ctx context.Context, arg MarkTenantDesiredEnabledBySubjectServiceWithGrantParams) (int64, error)
	//MarkTenantReconciled
	//
	//  UPDATE tenant_instances
	//  SET last_reconciled_at = ?1,
	//      last_error = NULLIF(?2, ''),
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE tenant_id = ?3
	MarkTenantReconciled(ctx context.Context, arg MarkTenantReconciledParams) error
	//MarkTenantRuntimeSpec
	//
	//  UPDATE tenant_instances
	//  SET runtime_spec_id = ?1,
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE tenant_id = ?2
	MarkTenantRuntimeSpec(ctx context.Context, arg MarkTenantRuntimeSpecParams) error
	//PruneExpiredDeviceAuthorizations
	//
	//  DELETE FROM oauth_device_authorizations
	//  WHERE status IN ('expired', 'denied', 'consumed')
	//    AND updated_at <= ?1
	PruneExpiredDeviceAuthorizations(ctx context.Context, arg PruneExpiredDeviceAuthorizationsParams) (int64, error)
	//PutBrowserSession
	//
	//  INSERT INTO edge_browser_sessions (session_id, subject_sub, claims, expires_at, updated_at)
	//  VALUES (?1, NULLIF(?2, ''), ?3, ?4, CURRENT_TIMESTAMP)
	//  ON CONFLICT(session_id) DO UPDATE SET subject_sub = excluded.subject_sub, claims = excluded.claims, expires_at = excluded.expires_at, updated_at = CURRENT_TIMESTAMP
	PutBrowserSession(ctx context.Context, arg PutBrowserSessionParams) error
	//PutPendingLogin
	//
	//  INSERT INTO edge_pending_logins (state, return_to, nonce, expires_at, updated_at)
	//  VALUES (?1, ?2, ?3, ?4, CURRENT_TIMESTAMP)
	//  ON CONFLICT(state) DO UPDATE SET return_to = excluded.return_to, nonce = excluded.nonce, expires_at = excluded.expires_at, updated_at = CURRENT_TIMESTAMP
	PutPendingLogin(ctx context.Context, arg PutPendingLoginParams) error
	//RebuildEffectiveServiceGrants
	//
	//  DELETE FROM service_grants
	RebuildEffectiveServiceGrants(ctx context.Context) error
	//ReleaseControlPlaneLease
	//
	//  DELETE FROM control_plane_leases
	//  WHERE lease_name = ?1
	//      AND holder_id = ?2
	ReleaseControlPlaneLease(ctx context.Context, arg ReleaseControlPlaneLeaseParams) error
	//RevokeMemoryBankProjectShare
	//
	//  UPDATE memory_bank_project_shares
	//  SET state = 'revoked',
	//      revoked_at = ?1,
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE share_id = ?2
	//    AND state <> 'revoked'
	RevokeMemoryBankProjectShare(ctx context.Context, arg RevokeMemoryBankProjectShareParams) (int64, error)
	//SlowDownDeviceAuthorizationPoll
	//
	//  UPDATE oauth_device_authorizations
	//  SET last_poll_at = ?1,
	//      poll_count = poll_count + 1,
	//      interval_seconds = interval_seconds + ?2,
	//      updated_at = ?1
	//  WHERE device_authorization_id = ?3
	SlowDownDeviceAuthorizationPoll(ctx context.Context, arg SlowDownDeviceAuthorizationPollParams) (int64, error)
	//UpdateDeviceAuthorizationPoll
	//
	//  UPDATE oauth_device_authorizations
	//  SET last_poll_at = ?1,
	//      poll_count = poll_count + 1,
	//      updated_at = ?1
	//  WHERE device_authorization_id = ?2
	UpdateDeviceAuthorizationPoll(ctx context.Context, arg UpdateDeviceAuthorizationPollParams) (int64, error)
	//UpdateTenantRuntimeStatus
	//
	//  UPDATE tenant_instances
	//  SET runtime_state = ?1,
	//      coolify_resource_id = CASE WHEN CAST(?2 AS boolean) THEN NULL WHEN ?3 = '' THEN coolify_resource_id ELSE ?3 END,
	//      coolify_application_id = CASE WHEN ?2 THEN NULL WHEN ?4 = '' THEN coolify_application_id ELSE ?4 END,
	//      upstream_url = CASE WHEN ?2 THEN NULL WHEN ?5 = '' THEN upstream_url ELSE ?5 END,
	//      last_healthy_at = CASE WHEN ?2 THEN NULL WHEN ?6 IS NULL THEN last_healthy_at ELSE ?6 END,
	//      last_error = NULLIF(?7, ''),
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE tenant_id = ?8
	UpdateTenantRuntimeStatus(ctx context.Context, arg UpdateTenantRuntimeStatusParams) error
	//UpsertManualServiceGrantSource
	//
	//  INSERT INTO service_grant_sources (subject_sub, service_id, source_group, granted_at, last_synced_at)
	//  VALUES (?1, ?2, 'manual', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
	//  ON CONFLICT(subject_sub, service_id, source_group) DO UPDATE SET
	//      last_synced_at = CURRENT_TIMESTAMP,
	//      updated_at = CURRENT_TIMESTAMP
	UpsertManualServiceGrantSource(ctx context.Context, arg UpsertManualServiceGrantSourceParams) error
	//UpsertMemoryBankProject
	//
	//  INSERT INTO memory_bank_projects (project_id, owner_subject_sub, owner_tenant_id, service_id, project_key, display_name, root_path, metadata, archived_at)
	//  VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
	//  ON CONFLICT(owner_subject_sub, service_id, project_key) DO UPDATE SET
	//      owner_tenant_id = excluded.owner_tenant_id,
	//      display_name = excluded.display_name,
	//      root_path = excluded.root_path,
	//      metadata = excluded.metadata,
	//      archived_at = COALESCE(excluded.archived_at, memory_bank_projects.archived_at),
	//      updated_at = CURRENT_TIMESTAMP
	//  RETURNING project_id
	UpsertMemoryBankProject(ctx context.Context, arg UpsertMemoryBankProjectParams) ([]byte, error)
	//UpsertOAuthSession
	//
	//  INSERT INTO oauth_sessions (session_id, subject_sub, client_id, service_id, resource, redirect_uri, scope, code_challenge, code_challenge_method, authorization_code_hash, authorization_code_ciphertext, access_token_hash, access_token_ciphertext, refresh_token_hash, refresh_token_ciphertext, code_create_at, code_expires_in_seconds, access_create_at, access_expires_in_seconds, refresh_create_at, refresh_expires_in_seconds, expires_at, issued_via, operator_reason, authorization_details, policy_binding_id, share_id, consumed_at, updated_at)
	//  VALUES (?1, NULLIF(?2, ''), ?3, NULLIF(?4, ''), ?5, ?6, ?7, NULLIF(?8, ''), NULLIF(?9, ''), ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18, ?19, ?20, ?21, ?22, ?23, ?24, ?25, ?26, NULLIF(?27, X''), NULL, CURRENT_TIMESTAMP)
	//  ON CONFLICT(session_id) DO UPDATE SET
	//      subject_sub = excluded.subject_sub,
	//      client_id = excluded.client_id,
	//      service_id = excluded.service_id,
	//      resource = excluded.resource,
	//      redirect_uri = excluded.redirect_uri,
	//      scope = excluded.scope,
	//      code_challenge = excluded.code_challenge,
	//      code_challenge_method = excluded.code_challenge_method,
	//      authorization_code_hash = excluded.authorization_code_hash,
	//      authorization_code_ciphertext = excluded.authorization_code_ciphertext,
	//      access_token_hash = excluded.access_token_hash,
	//      access_token_ciphertext = excluded.access_token_ciphertext,
	//      refresh_token_hash = excluded.refresh_token_hash,
	//      refresh_token_ciphertext = excluded.refresh_token_ciphertext,
	//      code_create_at = excluded.code_create_at,
	//      code_expires_in_seconds = excluded.code_expires_in_seconds,
	//      access_create_at = excluded.access_create_at,
	//      access_expires_in_seconds = excluded.access_expires_in_seconds,
	//      refresh_create_at = excluded.refresh_create_at,
	//      refresh_expires_in_seconds = excluded.refresh_expires_in_seconds,
	//      expires_at = excluded.expires_at,
	//      issued_via = excluded.issued_via,
	//      operator_reason = excluded.operator_reason,
	//      authorization_details = excluded.authorization_details,
	//      policy_binding_id = excluded.policy_binding_id,
	//      share_id = excluded.share_id,
	//      consumed_at = NULL,
	//      updated_at = CURRENT_TIMESTAMP
	UpsertOAuthSession(ctx context.Context, arg UpsertOAuthSessionParams) error
	//UpsertServiceCatalogEntry
	//
	//  INSERT INTO service_catalog (
	//      service_id,
	//      display_name,
	//      upstream_service_name,
	//      transport_type,
	//      internal_port,
	//      public_path,
	//      internal_upstream_path,
	//      health_path,
	//      health_probe_expectation,
	//      resource_profile,
	//      persistence_policy,
	//      adapter_requirement,
	//      secret_contract,
	//      identity_context,
	//      enabled,
	//      source,
	//      updated_at
	//  )
	//  VALUES (
	//      ?1,
	//      ?2,
	//      ?3,
	//      ?4,
	//      ?5,
	//      ?6,
	//      ?7,
	//      ?8,
	//      ?9,
	//      ?10,
	//      ?11,
	//      ?12,
	//      ?13,
	//      ?14,
	//      ?15,
	//      ?16,
	//      CURRENT_TIMESTAMP
	//  )
	//  ON CONFLICT(service_id) DO UPDATE SET
	//      display_name = excluded.display_name,
	//      upstream_service_name = excluded.upstream_service_name,
	//      transport_type = excluded.transport_type,
	//      internal_port = excluded.internal_port,
	//      public_path = excluded.public_path,
	//      internal_upstream_path = excluded.internal_upstream_path,
	//      health_path = excluded.health_path,
	//      health_probe_expectation = excluded.health_probe_expectation,
	//      resource_profile = excluded.resource_profile,
	//      persistence_policy = excluded.persistence_policy,
	//      adapter_requirement = excluded.adapter_requirement,
	//      enabled = excluded.enabled,
	//      secret_contract = excluded.secret_contract,
	//      identity_context = excluded.identity_context,
	//      source = excluded.source,
	//      updated_at = CURRENT_TIMESTAMP
	UpsertServiceCatalogEntry(ctx context.Context, arg UpsertServiceCatalogEntryParams) error
	//UpsertStaticTenantUpstream
	//
	//  INSERT INTO tenant_instances (
	//      tenant_id,
	//      subject_sub,
	//      service_id,
	//      subject_key,
	//      tenant_instance_name,
	//      internal_dns_name,
	//      desired_state,
	//      runtime_state,
	//      upstream_url,
	//      last_healthy_at,
	//      last_error,
	//      metadata
	//  )
	//  VALUES (
	//      ?1,
	//      ?2,
	//      ?3,
	//      ?4,
	//      ?5,
	//      ?6,
	//      'enabled',
	//      'ready',
	//      ?7,
	//      ?8,
	//      NULL,
	//      json_object('runtime_mode', 'static_upstream')
	//  )
	//  ON CONFLICT(subject_sub, service_id) DO UPDATE SET
	//      subject_key = excluded.subject_key,
	//      tenant_instance_name = excluded.tenant_instance_name,
	//      internal_dns_name = excluded.internal_dns_name,
	//      desired_state = 'enabled',
	//      runtime_state = 'ready',
	//      coolify_resource_id = NULL,
	//      coolify_application_id = NULL,
	//      upstream_url = excluded.upstream_url,
	//      last_healthy_at = excluded.last_healthy_at,
	//      last_error = NULL,
	//      metadata = json_patch(tenant_instances.metadata, excluded.metadata),
	//      updated_at = CURRENT_TIMESTAMP
	UpsertStaticTenantUpstream(ctx context.Context, arg UpsertStaticTenantUpstreamParams) error
	//UpsertSubject
	//
	//  INSERT INTO subjects (subject_sub, subject_key, preferred_username, email, display_name, account_binding_id, account_binding_claim, last_synced_at, updated_at)
	//  VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
	//  ON CONFLICT(subject_sub) DO UPDATE SET
	//      subject_key = excluded.subject_key,
	//      preferred_username = excluded.preferred_username,
	//      email = excluded.email,
	//      display_name = excluded.display_name,
	//  	account_binding_id = excluded.account_binding_id,
	//  	account_binding_claim = excluded.account_binding_claim,
	//      last_synced_at = CURRENT_TIMESTAMP,
	//      updated_at = CURRENT_TIMESTAMP
	UpsertSubject(ctx context.Context, arg UpsertSubjectParams) error
	//UpsertSubjectPreservingMetadata
	//
	//  INSERT INTO subjects (subject_sub, subject_key, preferred_username, email, display_name, account_binding_id, account_binding_claim, last_synced_at, updated_at)
	//  VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
	//  ON CONFLICT(subject_sub) DO UPDATE SET
	//      subject_key = subjects.subject_key,
	//      preferred_username = COALESCE(excluded.preferred_username, subjects.preferred_username),
	//      email = COALESCE(excluded.email, subjects.email),
	//      display_name = COALESCE(excluded.display_name, subjects.display_name),
	//  	account_binding_id = COALESCE(excluded.account_binding_id, subjects.account_binding_id),
	//  	account_binding_claim = COALESCE(excluded.account_binding_claim, subjects.account_binding_claim),
	//      updated_at = CURRENT_TIMESTAMP
	UpsertSubjectPreservingMetadata(ctx context.Context, arg UpsertSubjectPreservingMetadataParams) error
}

var _ Querier = (*Queries)(nil)
